name: sumup

config-version: 2

profile: sumup_postgres

model-paths: ["models"]

seed-paths: ["raw_data"]

models:
  sumup:
    stg:
      +schema: stg
      +materialized: table
    mart:
      +materialized: table



seeds:
  sumup:
    +schema: raw
    tags:
      - raw_source_load
