version: 2

models:
  - name: dim_device
    description: "Staging table for device data."
    columns:
      - name: id
        description: "Unique ID of the device. PK."
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: device_src_id
        description: "Original device ID from the source table."
        data_type: integer
        tests:
          - not_null

      - name: type
        description: "Device type."
        data_type: int

      - name: store_id
        description: "ID of the store linked to the device. FK."
        data_type: varchar
        tests:
          - not_null

    tags:
      - DIM
      - device
