version: 2

models:
  - name: dim_store
    description: "Staging table for store data."
    columns:
      - name: id
        description: "Unique ID of the store. PK."
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: store_src_id
        description: "Original store ID from the source table."
        data_type: integer
        tests:
          - not_null

      - name: name
        description: "Store name."
        data_type: varchar
        tests:
          - not_null

      - name: address
        description: "Store address."
        data_type: varchar

      - name: city
        description: "Store city."
        data_type: varchar

      - name: country
        description: "Store country."
        data_type: varchar
        tests:
          - not_null

      - name: created_at
        description: "Store creation timestamp."
        data_type: timestamp
        tests:
          - not_null

      - name: typology
        description: "Store type."
        data_type: varchar

      - name: customer_id
        description: "ID of the customer. FK."
        data_type: varchar

    tags:
      - DIM
      - store
