version: 2

models:
  - name: l_device_x_store
    description: "Link between devices and stores."
    columns:
      - name: device_id
        description: "Unique ID of the device."
        data_type: varchar
        tests:
          - not_null

      - name: store_id
        description: "ID of the store linked to the device."
        data_type: varchar
        tests:
          - not_null
