version: 2

models:
  - name: stg_product
    description: "Staging table for product data."
    columns:
      - name: id
        description: "Unique product ID (MD5 hash of product_sku and product_name)."
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: product_sku
        description: "SKU of the product."
        data_type: varchar
        tests:
          - not_null

      - name: category_name
        description: "Category name of the product."
        data_type: varchar
        tests:
          - not_null
